export enum GameStatusEnum {
  BEFORE_STARTING,
  LOADING,
  RUNNING,
  PAUSED,
  WON,
  LOST,
  ERROR,
}

export enum GameActionTypeEnum {
  START_GAME = 'START_GAME',
  GET_NEW_POKEMON = 'GET_NEW_POKEMON',
  CLICK_LETTER = 'CLICK_LETTER',
  UPDATE_STATUS = 'UPDATE_STATUS',
  CHANGE_GENERATION = 'CHANGE_GENERATION'
}
